# Generated by Django 2.2.6 on 2020-07-13 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20200713_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 13, 21, 49, 53, 4072)),
        ),
    ]
