# Generated by Django 2.2.6 on 2020-07-14 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20200713_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 14, 8, 36, 41, 581861)),
        ),
    ]
