# Generated by Django 2.2.6 on 2020-07-19 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_auto_20200719_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 19, 10, 16, 18, 44526)),
        ),
    ]
