# Generated by Django 2.2.6 on 2020-07-19 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0023_auto_20200719_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 19, 15, 9, 38, 245137)),
        ),
    ]
