# Generated by Django 2.2.6 on 2020-07-19 04:21

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0018_auto_20200715_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='mute',
            field=models.ManyToManyField(blank=True, default=None, related_name='mute_title', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articles',
            name='subscribe',
            field=models.ManyToManyField(blank=True, default=None, related_name='subscribe_title', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 19, 9, 51, 33, 872285)),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 19, 9, 51, 33, 862258)),
        ),
        migrations.DeleteModel(
            name='titleview',
        ),
    ]
