# Generated by Django 2.2.6 on 2020-07-14 03:14

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poetries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poetries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=150, unique=True)),
                ('project_name', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('date_Publish', models.DateField(default=datetime.datetime.now)),
                ('date_updated', models.DateField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='users/images')),
                ('video', models.FileField(blank=True, null=True, upload_to='users/video', verbose_name='Video')),
                ('image2', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('link', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('time', models.TimeField(default=datetime.datetime(2020, 7, 14, 8, 44, 16, 543090))),
                ('tags', models.CharField(default='', help_text='Add comma( ,) seperated tags!!', max_length=300, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('method', models.CharField(choices=[('content', 'content'), ('design', 'design'), ('editor', 'editor')], default='content', max_length=10)),
                ('template', models.CharField(blank=True, max_length=1000, null=True)),
                ('quora', models.CharField(blank=True, max_length=1000, null=True)),
                ('medium', models.CharField(blank=True, max_length=1000, null=True)),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='category3', to='poetries.Categories', to_field='category_name')),
                ('disliked', models.ManyToManyField(blank=True, default=None, related_name='dislikes_poetries', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, default=None, related_name='likes_poetries', to=settings.AUTH_USER_MODEL)),
                ('user_poetries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user3', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ('date_Publish', 'time'),
            },
        ),
        migrations.AlterField(
            model_name='poetries_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poetris_comments', to='poetries.Poetries'),
        ),
        migrations.AlterField(
            model_name='titleview',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poetriesview', to='poetries.Poetries', to_field='title'),
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
