# Generated by Django 2.2.6 on 2020-07-15 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetries', '0007_auto_20200715_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetries',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 15, 17, 27, 10, 787371)),
        ),
    ]
