# Generated by Django 2.2.6 on 2020-07-15 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetries', '0008_auto_20200715_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetries',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 15, 20, 59, 10, 472482)),
        ),
    ]
