# Generated by Django 2.2.6 on 2020-07-15 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetries', '0009_auto_20200715_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetries',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 15, 21, 4, 53, 724324)),
        ),
    ]
