# Generated by Django 2.2.6 on 2020-07-15 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetries', '0011_auto_20200715_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetries',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 15, 22, 3, 36, 376693)),
        ),
    ]
