# Generated by Django 2.2.6 on 2020-07-19 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetries', '0017_auto_20200719_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetries',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 19, 17, 56, 30, 408749)),
        ),
    ]
