# Generated by Django 2.2.6 on 2020-07-14 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 14, 8, 39, 23, 466384)),
        ),
    ]
