# Generated by Django 2.2.6 on 2020-07-14 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200714_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 14, 9, 6, 47, 197889)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=150, unique=True),
        ),
    ]
