# Generated by Django 2.2.6 on 2020-07-14 03:51

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20200714_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 14, 9, 21, 6, 136691)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='titleview',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoteview', to='quotes.Quotes', to_field='content'),
        ),
    ]
