# Generated by Django 2.2.6 on 2020-07-15 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20200715_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 15, 17, 21, 28, 127582)),
        ),
    ]
