# Generated by Django 2.2.6 on 2020-07-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_auto_20200719_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes_comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='quotes_comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='titleview',
            name='view',
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
        migrations.DeleteModel(
            name='Quotes_comment',
        ),
        migrations.DeleteModel(
            name='titleview',
        ),
    ]
