# Generated by Django 2.2.6 on 2020-07-19 10:10

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0017_auto_20200719_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50)),
                ('date_Publish', models.DateField(default=datetime.datetime.now)),
                ('date_updated', models.DateField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='users/images')),
                ('content', ckeditor.fields.RichTextField(null=True, unique=True)),
                ('link', models.TextField(blank=True, default='')),
                ('time', models.TimeField(default=datetime.datetime(2020, 7, 19, 15, 40, 54, 914239))),
                ('tags', models.CharField(default='', help_text='Add comma( ,) seperated tags!!', max_length=300, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('quora', models.CharField(blank=True, max_length=1000, null=True)),
                ('medium', models.CharField(blank=True, max_length=1000, null=True)),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=1000, null=True)),
                ('other', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='quotes.Categories', to_field='category_name')),
                ('disliked', models.ManyToManyField(blank=True, default=None, related_name='dislikes_quotes', to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(blank=True, default=None, related_name='likes_quotes', to=settings.AUTH_USER_MODEL)),
                ('user_quotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ('date_Publish', 'time'),
            },
        ),
    ]
