# Generated by Django 2.2.6 on 2020-07-19 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_quotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 19, 17, 56, 30, 415576)),
        ),
    ]
