# Generated by Django 2.2.6 on 2020-07-25 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_auto_20200719_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 25, 11, 15, 5, 4997)),
        ),
    ]
