# Generated by Django 2.2.6 on 2020-07-25 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_auto_20200725_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 25, 16, 25, 50, 786499)),
        ),
    ]
